# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wgtTop = QtWidgets.QWidget(self.centralWidget)
        self.wgtTop.setObjectName("wgtTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wgtTop)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edtFilePath = QtWidgets.QLineEdit(self.wgtTop)
        self.edtFilePath.setEnabled(False)
        self.edtFilePath.setText("")
        self.edtFilePath.setObjectName("edtFilePath")
        self.horizontalLayout.addWidget(self.edtFilePath)
        self.btnBrowse = QtWidgets.QPushButton(self.wgtTop)
        self.btnBrowse.setEnabled(True)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.verticalLayout.addWidget(self.wgtTop)
        self.wgtBottom = QtWidgets.QWidget(self.centralWidget)
        self.wgtBottom.setObjectName("wgtBottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wgtBottom)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wgtControllerStart = QtWidgets.QWidget(self.wgtBottom)
        self.wgtControllerStart.setObjectName("wgtControllerStart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wgtControllerStart)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStartEnd = QtWidgets.QPushButton(self.wgtControllerStart)
        self.btnStartEnd.setMinimumSize(QtCore.QSize(70, 0))
        self.btnStartEnd.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btnStartEnd.setCheckable(True)
        self.btnStartEnd.setObjectName("btnStartEnd")
        self.horizontalLayout_3.addWidget(self.btnStartEnd)
        self.sliderSpeed = QtWidgets.QSlider(self.wgtControllerStart)
        self.sliderSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSpeed.setObjectName("sliderSpeed")
        self.horizontalLayout_3.addWidget(self.sliderSpeed)
        self.verticalLayout_3.addWidget(self.wgtControllerStart)
        self.verticalLayout.addWidget(self.wgtBottom)
        self.wgtTest = QtWidgets.QWidget(self.centralWidget)
        self.wgtTest.setObjectName("wgtTest")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wgtTest)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.wgtTest)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.wgtController = QtWidgets.QWidget(self.wgtTest)
        self.wgtController.setObjectName("wgtController")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wgtController)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnTest = QtWidgets.QPushButton(self.wgtController)
        self.btnTest.setMinimumSize(QtCore.QSize(70, 0))
        self.btnTest.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btnTest.setCheckable(True)
        self.btnTest.setObjectName("btnTest")
        self.horizontalLayout_4.addWidget(self.btnTest)
        self.sliderPumper = QtWidgets.QSlider(self.wgtController)
        self.sliderPumper.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPumper.setObjectName("sliderPumper")
        self.horizontalLayout_4.addWidget(self.sliderPumper)
        self.verticalLayout_2.addWidget(self.wgtController)
        self.verticalLayout.addWidget(self.wgtTest)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pancake"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.btnStartEnd.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Pump Test"))
        self.btnTest.setText(_translate("MainWindow", "Test"))

